### ISSUE TITLE
Question: FloodGate for Sponge?

### ISSUE THREAD

**Issue by myxxmikeyxx** [GeyserMC/GeyserWiki#190]
Question on: _docs/floodgate/setup.md
I don't see a setup for sponge server.
Will you have one like gyser or no?
Is it needed?
Will floodgate support the sponge API version 11 for mc 1.20.1?

Different question:
Does gyser sponge verson support 1.20.1 API version 11 or just the 1.12.1 API 8?
It does not say on the donwload page for sponge what version.

**Comment by Konicai** [comment]
Just an fyi, Geyser-Sponge will be removed in the upcoming months.

**Comment by onebeastchris** [comment]
Sponge is (from what I can tell) an overly ambitious platform that was never fully ready. If you want vanilla mechanics including all bugs, go with Fabric - using server side mods, you would have the equivalent of plugins.

Or just.. use paper with a plugin bringing back that mechanic.

Regardless; I'd close this since Floodgate-Sponge is unlikely to be made (you could open a feature request for it over at the floodgate repository; but it's unlikely since we are dropping Geyser-Sponge soon).

**Comment by myxxmikeyxx** [comment]
@onebeastchris Okay, thank you for the input. I like sponge so far but it doesn't work with a lot of datapacks or plugins. For papermc, it seems that it is not common for most players so I haven't found a plugin for it. I do like that sponge supports forge mods but fabric seems to be taking over. Fabric seems easy to make mods for, but it can be a lot more restrictive when making complex mods so they have to code more to make it work with fabric, from what I've seen.

**Comment by Konicai** [comment]
Just an fyi - Sponge doesn't support forge mods. SpongeForge is a Forge mod that adds support for Sponge plugins.

Geyser-Forge is currently in development, and although this is not a promise or official statement, floodgate-forge has a much higher chance of being developed in the future than floodgate-sponge. 

Geyser-Sponge will be dropped when Geyser-Forge is released.

**Comment by myxxmikeyxx** [comment]
Thought sponge forge was well sponge but the support for forge mods and plugins, my mistake.

Geyser Forge will be cool for people who mod.
