### ISSUE TITLE
Can Geyser1.16 be restored?

### ISSUE THREAD

**Issue by HangZhouXZH** [GeyserMC/GeyserWiki#29]
I hope to restore Geyser's 1.16,1.17 running on my device is too stuck. 
(Translation is not necessarily 100% accurate)

**Comment by Jens-Co** [comment]
Hello there!
First of all this is the GeyserWiki repository, if you are having issues with Geyser you can create a new issue here (https://github.com/GeyserMC/Geyser/issues)

If you create an issue please fill in the full issue template with as much info as you can give us.

I will close this issue here.
