### ISSUE TITLE
Improve local linking doc

### ISSUE THREAD

**Issue by keliansb** [GeyserMC/GeyserWiki#69]
Hi all,

I think the documentation about the local linking is not very clear.

It is mentioned that the linking databases extensions and the configuration have to be done only on the proxy, but in this case the `/linkaccount` command is not available on the backend servers.
Shouldn't floodgate also be installed on these servers?
And if so, what configuration should be applied?

**Comment by Konicai** [comment]
The docs are correct, floodgate only needs to be installed on the proxy for linking to work (and it wont work on the backend).

The /linkaccount command is available on the proxy because thats where you installed floodgate and setup linking.

I feel its clear enough that if you're using a proxy, floodgate on the proxy manages linking. Is there anything else?

**Comment by keliansb** [comment]
Thanks for your answer. If I install floodgate only on the proxy I don't have access to the `/linkaccount` command in the game. Am I missing something?

**Comment by Konicai** [comment]
Probably a permission :P

**Comment by keliansb** [comment]
I finally got the local linking to work! It was indeed missing permissions, I installed the LuckPerms plugin and allowed the permissions mentioned [here](https://wiki.geysermc.org/floodgate/commands/). Thanks for your help!
